# options_screening/config.yaml

# Debug logging
debug_logging: false  # Set to true to enable debug logging

# Data fetching parameters
data:
  tickers:
    - AAPL
    - GOOGL
    - MSFT
    - AMZN
    - META
    - NVDA
    - TSLA
    - AMD
    - INTC
    - IBM
  start_date: '2023-01-01'
  end_date: '2024-07-05' # 'auto' will use the current date

# Feature engineering parameters
features:
  types:
    - basic
    - technical
    - advanced
  basic:
    - moneyness
    - time_to_expiry
    - historical_volatility_10d
    - historical_volatility_30d
    - historical_volatility_60d
    - volume_oi_ratio
  technical:
    - rsi
    - macd
    - bollinger_bands
    - moving_average_50
    - moving_average_200
  advanced:
    - implied_volatility
    - delta
    - gamma
    - theta
    - vega
  fundamental:
    - pe_ratio
    - dividend_yield
    - beta

target:
  type: profit  # or 'delta_profit' to use the new target
  params:
    profit_threshold: 0.005
    delta_threshold: 0.5  # This will be ignored for 'profit' target type

cross_validation:
  n_folds: 5

# Add a new section for model parameters
model_params:
  neural_network:
    positive_threshold: 0.3  # Adjust this value to change the threshold for positive class

# Model parameters
models:
  - name: RandomForest
    type: RandomForestClassifier
    params:
      n_estimators: 100
      random_state: 42
      class_weight: balanced
  - name: GradientBoosting
    type: GradientBoostingClassifier
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42
  - name: NeuralNetwork
    type: NeuralNetworkModel
    params: {}  # We don't need to pass parameters here as they're defined in the model class

# Preprocessing parameters
preprocessing:
  imputer_strategy: mean
  scaler: StandardScaler

# Visualization parameters
visualization:
  feature_importance_plot:
    figsize: [12, 6]
    rotation: 45