# options_screening/config.yaml

# Debug logging
debug_logging: false  # Set to true to enable debug logging

# Data fetching parameters
data:
  tickers:
    - AAPL
    - GOOGL
    - MSFT
    - AMZN
    - META
    - NVDA
    - TSLA
    - AMD
    - INTC
    - IBM
  start_date: '2022-01-01'
  end_date: 'auto' # 'auto' will use the current date

# Feature engineering parameters
features:
  basic:
    - moneyness
    - time_to_expiry
    - historical_volatility
    - volume_oi_ratio
  advanced:
    - implied_volatility
    - delta
    - gamma
    - theta
    - vega
    - price_to_strike
    - price_to_underlying
    - iv_to_hv_ratio
    - oi_to_volume_ratio

# Add a new section for model parameters
model_params:
  neural_network:
    positive_threshold: 0.3  # Adjust this value to change the threshold for positive class

# Model parameters
models:
  - name: RandomForest
    type: RandomForestClassifier
    params:
      n_estimators: 100
      random_state: 42
      class_weight: balanced
  - name: GradientBoosting
    type: GradientBoostingClassifier
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42
  - name: NeuralNetwork
    type: NeuralNetworkModel
    params: {}  # We don't need to pass parameters here as they're defined in the model class

# Preprocessing parameters
preprocessing:
  imputer_strategy: mean
  scaler: StandardScaler

# Visualization parameters
visualization:
  feature_importance_plot:
    figsize: [12, 6]
    rotation: 45